### ISSUE TITLE
disableSecureView in npm package

### ISSUE THREAD

**Issue by smbryar** [killserver/react-native-screenshot-prevent#12]
Hi there,

Thanks for this very helpful package! Do you have a plan on when `disableSecureView` will be available in the npm package?

Thanks,
Saoirse

**Comment by smbryar** [comment]
I have added this PR which I think is all that is needed https://github.com/killserver/react-native-screenshot-prevent/pull/13

**Comment by killserver** [comment]
> Hi there,
> 
> Thanks for this very helpful package! Do you have a plan on when `disableSecureView` will be available in the npm package?
> 
> Thanks, Saoirse

thx for use ) method "disableSecureView" already in npm, but without types ) added your PR, a little bit later publish on npm

**Comment by killserver** [comment]
upload )
