### ISSUE TITLE
Error pod install

### ISSUE THREAD

**Issue by ajiehatajie** [killserver/react-native-screenshot-prevent#19]
[!] The `RNScreenshotPrevent` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.

❯

**Comment by aerhakim** [comment]
any solution about above error?

**Comment by killserver** [comment]
Version latest? Try use version 1.1.1 of repeat problem

**Comment by RVassili** [comment]
The issue has been introduce in the commit [06837de](https://github.com/killserver/react-native-screenshot-prevent/commit/06837de5373b5bfd27708493b619726c40a77d2a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L18-L20)

To fix this you can update RNScreenshotPrevent.podspec ligne 12 with:
`  s.homepage     = "https://github.com/killserver/react-native-screenshot-prevent"`
and run `yarn patch-package react-native-screenshot-prevent`

**Comment by killserver** [comment]
thx. I not clear cache in build and not see this problem ) fix in 1.1.4
