### ISSUE TITLE
Cannot find module 'react-native-screenshot-prevent' or its corresponding type declarations.

### ISSUE THREAD

**Issue by AhmedSamir74** [killserver/react-native-screenshot-prevent#22]
![image](https://github.com/killserver/react-native-screenshot-prevent/assets/63313849/6b3f0c18-43c6-4c0b-926c-683928f834bd)

Hi @killserver I got this error after installing version 1.1.4.
I installed it using yarn

**Comment by aabid00177** [comment]
Hey @AhmedSamir74 ,
I also faced this error, Actually index.js file is missing in npm
Please add this index.js file manually in react-native-screenshot-prevent folder under node_modules

File URL: https://www.npmjs.com/package/react-native-screenshot-prevent/v/1.1.1?activeTab=code

**Comment by killserver** [comment]
pls, check 1.1.6 version

**Comment by tomruijgrok** [comment]
Version 1.1.6 didn't fix the issue for me @killserver 
Adding index.ts with the correct content in the root directory did solve the issue.

**Comment by sssajjad007** [comment]
same error

**Comment by killserver** [comment]
pls check now. thx

**Comment by killserver** [comment]
answer not send. I close this issue. if error still exist - pls, reopen this issue. Thx

**Comment by iamvishaldev** [comment]
> Version 1.1.6 didn't fix the issue for me @killserver Adding index.ts with the correct content in the root directory did solve the issue.

Can you Please provide the code from index.ts

TypeError: _reactNativeScreenshotPrevent.default.prevent is not a function. (In '_reactNativeScreenshotPrevent.default.prevent()', '_reactNativeScreenshotPrevent.default.prevent' is undefined)
