### ISSUE TITLE
App becomes unresponsive if minimized and re-opened

### ISSUE THREAD

**Issue by tahasabih** [killserver/react-native-screenshot-prevent#33]
If the `RNScreenshotPrevent.enableSecureView()` function is called in a React Native app then the app is minimized and re-opened, the app stops responding. Calling `RNScreenshotPrevent.disableSecureView()` does not help - app stays unresponsive regardless.

iOS only issue - tested with iOS 17.0.3

**Comment by tahasabih** [comment]
This was a conflict with another library. Closing.

**Comment by quanKM** [comment]
Hi @tahasabih, I have had the same problems as you. May I ask which package you used and how you resolved the issue?
