### ISSUE TITLE
Android build with react native 0.70 fails

### ISSUE THREAD

**Issue by PrajwalTS-Blackbuck** [killserver/react-native-screenshot-prevent#5]
The error : 
A problem occurred evaluating project ':react-native-screenshot-prevent'.
> Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by killserver** [comment]
try latest version from npm

**Comment by PrajTS** [comment]
Thanks for the new release
