### ISSUE TITLE
Android instalation errors solved

### ISSUE THREAD

**Issue by JoseCarlos33** [killserver/react-native-screenshot-prevent#9]
Hello, I really like your library! I only had a few problems in installation of library at android app, but after some tests I find a way to fix just changing a configuration, if be useful for another people following this steps to configurate the library on android:

1. Open up `android/app/src/main/java/[YOUR_PROJECT_NAME]/MainApplication.java`
  - Add `import com.killserver.screenshotprev.RNScreenshotPreventPackage;` to the imports at the top of the file;
  
2. Append the following lines to `android/settings.gradle`:
  	```
  	include ':react-native-screenshot-prevent'
  	project(':react-native-screenshot-prevent').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-screenshot-prevent/android')
  	```
  	
3. Insert the following lines inside the dependencies block in `android/app/build.gradle`:
  	```
      compile project(':react-native-screenshot-prevent')
  	```

**Comment by killserver** [comment]
Hello. Thx) But .. this writes in "manual installation" block)

**Comment by JoseCarlos33** [comment]
Hello, I put this because have small details that generate errors in the installation, for example instead MainActivity.java I put here MainApplicationJava, and not add new RNPreventScreenshotPackages. In import of RNScreenshotPreventPackage, instead com.killserver.RNPreventScreenshotPackage; I put com.killserver.screenshotprev.RNScreenshotPreventPackage; because the path package have a folder screenshotprev missing in documentation;

**Comment by killserver** [comment]
> Hello, I put this because have small details that generate errors in the installation, for example instead MainActivity.java I put here MainApplicationJava, and not add new RNPreventScreenshotPackages. In import of RNScreenshotPreventPackage, instead com.killserver.RNPreventScreenshotPackage; I put com.killserver.screenshotprev.RNScreenshotPreventPackage; because the path package have a folder screenshotprev missing in documentation;

thx, fix README. please check
